# Generated by Django 3.1.4 on 2020-12-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201218_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workerprofile',
            options={'ordering': ['-views']},
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='fullname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
