# Generated by Django 3.1.4 on 2020-12-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201218_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='workercategory',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workingarea',
            name='slug',
            field=models.SlugField(default='demo'),
            preserve_default=False,
        ),
    ]
