# Generated by Django 3.1.4 on 2020-12-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201220_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
